services:
  app:
    container_name: MyExpensesBot
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SERVICE_ACCOUNT_BASE64:
      SPREADSHEET_ID:
      BOT_TOKEN:
      CHAT_ID:
      OPENAI_API_KEY:
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M